site_name: FinishingM248
theme:
  name: readthedocs

markdown_extensions:
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 2

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
